/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as StrokeEmergencyChennaiRouteImport } from './routes/stroke-emergency-chennai'
import { Route as StrokeHospitalsChennaiRouteImport } from './routes/stroke-hospitals-chennai'
import { Route as StrokeRecoveryChennaiRouteImport } from './routes/stroke-recovery-chennai'
import { Route as StrokeSymptomsChennaiRouteImport } from './routes/stroke-symptoms-chennai'
import { Route as StrokeTreatmentChennaiRouteImport } from './routes/stroke-treatment-chennai'
import { Route as ApiStrokeCallRouteImport } from './routes/api/stroke-call'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeEmergencyChennaiRoute = StrokeEmergencyChennaiRouteImport.update({
  id: '/stroke-emergency-chennai',
  path: '/stroke-emergency-chennai',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeHospitalsChennaiRoute = StrokeHospitalsChennaiRouteImport.update({
  id: '/stroke-hospitals-chennai',
  path: '/stroke-hospitals-chennai',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeRecoveryChennaiRoute = StrokeRecoveryChennaiRouteImport.update({
  id: '/stroke-recovery-chennai',
  path: '/stroke-recovery-chennai',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeSymptomsChennaiRoute = StrokeSymptomsChennaiRouteImport.update({
  id: '/stroke-symptoms-chennai',
  path: '/stroke-symptoms-chennai',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeTreatmentChennaiRoute = StrokeTreatmentChennaiRouteImport.update({
  id: '/stroke-treatment-chennai',
  path: '/stroke-treatment-chennai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrokeCallRoute = ApiStrokeCallRouteImport.update({
  id: '/api/stroke-call',
  path: '/api/stroke-call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/contact': typeof ContactRoute
  '/stroke-emergency-chennai': typeof StrokeEmergencyChennaiRoute
  '/stroke-hospitals-chennai': typeof StrokeHospitalsChennaiRoute
  '/stroke-recovery-chennai': typeof StrokeRecoveryChennaiRoute
  '/stroke-symptoms-chennai': typeof StrokeSymptomsChennaiRoute
  '/stroke-treatment-chennai': typeof StrokeTreatmentChennaiRoute
  '/api/stroke-call': typeof ApiStrokeCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/contact': typeof ContactRoute
  '/stroke-emergency-chennai': typeof StrokeEmergencyChennaiRoute
  '/stroke-hospitals-chennai': typeof StrokeHospitalsChennaiRoute
  '/stroke-recovery-chennai': typeof StrokeRecoveryChennaiRoute
  '/stroke-symptoms-chennai': typeof StrokeSymptomsChennaiRoute
  '/stroke-treatment-chennai': typeof StrokeTreatmentChennaiRoute
  '/api/stroke-call': typeof ApiStrokeCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/contact': typeof ContactRoute
  '/stroke-emergency-chennai': typeof StrokeEmergencyChennaiRoute
  '/stroke-hospitals-chennai': typeof StrokeHospitalsChennaiRoute
  '/stroke-recovery-chennai': typeof StrokeRecoveryChennaiRoute
  '/stroke-symptoms-chennai': typeof StrokeSymptomsChennaiRoute
  '/stroke-treatment-chennai': typeof StrokeTreatmentChennaiRoute
  '/api/stroke-call': typeof ApiStrokeCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/contact'
    | '/stroke-emergency-chennai'
    | '/stroke-hospitals-chennai'
    | '/stroke-recovery-chennai'
    | '/stroke-symptoms-chennai'
    | '/stroke-treatment-chennai'
    | '/api/stroke-call'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/contact'
    | '/stroke-emergency-chennai'
    | '/stroke-hospitals-chennai'
    | '/stroke-recovery-chennai'
    | '/stroke-symptoms-chennai'
    | '/stroke-treatment-chennai'
    | '/api/stroke-call'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/contact'
    | '/stroke-emergency-chennai'
    | '/stroke-hospitals-chennai'
    | '/stroke-recovery-chennai'
    | '/stroke-symptoms-chennai'
    | '/stroke-treatment-chennai'
    | '/api/stroke-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ContactRoute: typeof ContactRoute
  StrokeEmergencyChennaiRoute: typeof StrokeEmergencyChennaiRoute
  StrokeHospitalsChennaiRoute: typeof StrokeHospitalsChennaiRoute
  StrokeRecoveryChennaiRoute: typeof StrokeRecoveryChennaiRoute
  StrokeSymptomsChennaiRoute: typeof StrokeSymptomsChennaiRoute
  StrokeTreatmentChennaiRoute: typeof StrokeTreatmentChennaiRoute
  ApiStrokeCallRoute: typeof ApiStrokeCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke-emergency-chennai': {
      id: '/stroke-emergency-chennai'
      path: '/stroke-emergency-chennai'
      fullPath: '/stroke-emergency-chennai'
      preLoaderRoute: typeof StrokeEmergencyChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke-hospitals-chennai': {
      id: '/stroke-hospitals-chennai'
      path: '/stroke-hospitals-chennai'
      fullPath: '/stroke-hospitals-chennai'
      preLoaderRoute: typeof StrokeHospitalsChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke-recovery-chennai': {
      id: '/stroke-recovery-chennai'
      path: '/stroke-recovery-chennai'
      fullPath: '/stroke-recovery-chennai'
      preLoaderRoute: typeof StrokeRecoveryChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke-symptoms-chennai': {
      id: '/stroke-symptoms-chennai'
      path: '/stroke-symptoms-chennai'
      fullPath: '/stroke-symptoms-chennai'
      preLoaderRoute: typeof StrokeSymptomsChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke-treatment-chennai': {
      id: '/stroke-treatment-chennai'
      path: '/stroke-treatment-chennai'
      fullPath: '/stroke-treatment-chennai'
      preLoaderRoute: typeof StrokeTreatmentChennaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stroke-call': {
      id: '/api/stroke-call'
      path: '/api/stroke-call'
      fullPath: '/api/stroke-call'
      preLoaderRoute: typeof ApiStrokeCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ContactRoute: ContactRoute,
  StrokeEmergencyChennaiRoute: StrokeEmergencyChennaiRoute,
  StrokeHospitalsChennaiRoute: StrokeHospitalsChennaiRoute,
  StrokeRecoveryChennaiRoute: StrokeRecoveryChennaiRoute,
  StrokeSymptomsChennaiRoute: StrokeSymptomsChennaiRoute,
  StrokeTreatmentChennaiRoute: StrokeTreatmentChennaiRoute,
  ApiStrokeCallRoute: ApiStrokeCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
