/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as UpdateHospitalRouteImport } from './routes/update-hospital'
import { Route as ApiStrokeCallRouteImport } from './routes/api/stroke-call'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateHospitalRoute = UpdateHospitalRouteImport.update({
  id: '/update-hospital',
  path: '/update-hospital',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStrokeCallRoute = ApiStrokeCallRouteImport.update({
  id: '/api/stroke-call',
  path: '/api/stroke-call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/review': typeof ReviewRoute
  '/update-hospital': typeof UpdateHospitalRoute
  '/api/stroke-call': typeof ApiStrokeCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/review': typeof ReviewRoute
  '/update-hospital': typeof UpdateHospitalRoute
  '/api/stroke-call': typeof ApiStrokeCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/review': typeof ReviewRoute
  '/update-hospital': typeof UpdateHospitalRoute
  '/api/stroke-call': typeof ApiStrokeCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/activity' | '/review' | '/update-hospital' | '/api/stroke-call'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity' | '/review' | '/update-hospital' | '/api/stroke-call'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/review'
    | '/update-hospital'
    | '/api/stroke-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  ReviewRoute: typeof ReviewRoute
  UpdateHospitalRoute: typeof UpdateHospitalRoute
  ApiStrokeCallRoute: typeof ApiStrokeCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update-hospital': {
      id: '/update-hospital'
      path: '/update-hospital'
      fullPath: '/update-hospital'
      preLoaderRoute: typeof UpdateHospitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stroke-call': {
      id: '/api/stroke-call'
      path: '/api/stroke-call'
      fullPath: '/api/stroke-call'
      preLoaderRoute: typeof ApiStrokeCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  ReviewRoute: ReviewRoute,
  UpdateHospitalRoute: UpdateHospitalRoute,
  ApiStrokeCallRoute: ApiStrokeCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
